services:
  minimalapi:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:8080"
      - "--url=${NGROK_DOMAIN}"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
